server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://cdb-57vtjqrv.gz.tencentcdb.com:10094/demo011701?useUnicode=true&characterEncoding=utf8
    username: demo011701
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    check-template-location: true
    content-type: text/html
    suffix: .html
  resources:
    static-locations: classpath:/static/
  jpa:
    show-sql: true

mybatis:
  type-aliases-package: cn.konngo.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

